version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PG_HOST=db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
      - ai_service

  ai_service:
    build: ./ai_service
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: